version: "3"

services:
  hai:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code
  notebook:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code/
    ports:
      - "0.0.0.0:1111:8888"
    expose:
      - "8888"
    command:
      jupyter notebook --allow-root
  hai_app:
    build: ./docker
    volumes:
      - ./:/code
    working_dir: /code/
    ports:
      - "1112:1112"
    command:
      gunicorn -w 4 app:app.server -b 0.0.0.0:1112
